version: '3'

services:
  web:
    image: poc/signalr-scale-out-web
    build:
      context: .
      dockerfile: Web/Dockerfile
    environment:
      - Redis__ConnectionString=${Redis__ConnectionString:-redis:6379, abortConnect=false}
      - ASPNETCORE_URLS=http://+:80
      #- ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "3010:80"

  web2:
    image: poc/signalr-scale-out-web
    environment:
      - Redis__ConnectionString=${Redis__ConnectionString:-redis:6379, abortConnect=false}
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "3011:80"

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"